name: integrity

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Link check
        run: SPHINXOPTS="-n -W -a -E" make linkcheck
